config/routes.rb
Credport::Application.routes.draw do
  use_doorkeeper do
    skip_controllers :applications
  end
  scope 'admin' do
    resources :applications, :controller => 'oauth_applications' do
      resources :identity_contexts
      resources :entity_contexts
      resources :connection_contexts
    end
  end
  match 'redirect_back' => 'oauth_applications#redirect_back_from_signup'

  mount DjMon::Engine => 'dj_mon'
  match '/auth/:provider/callback' => 'authcallbacks#create'

  # current_user routes
  get 'me' => 'users#me'
  get 'me/recommendations_to_approve' => 'reviews#me_to_approve'

  # user routes
  resources :u , :as => :users, :controller => "users" do
    post 'emails' => 'attributes#add_email_to_verify'
    post 'phones' => 'attributes#add_phone_to_verify'
    post 'websites' => 'attributes#add_website_to_verify' 
    post 'websites/:id/check' => 'attributes#check_website'
    post 'name' => 'attributes#change_name'
    post 'tagline' => 'attributes#change_tagline'
    post 'profilepictures' => 'attributes#add_profile_picture'
    post 'backgroundpicture' => 'attributes#add_background_picture'
    post 'remove_profile_picture' => "attributes#remove_profile_picture"
    
    # credport recommendations
    post 'reviews' => 'reviews#create'
    post 'reviews/request_by_email' => 'reviews#request_by_email'
    put 'reviews/:id/approve' => 'reviews#approve'
    delete 'reviews/:id' => 'reviews#destroy'
    get 'review' => 'reviews#show'
    put 'review' => 'reviews#update'
    get ':mode' => 'users#show'
  end

  post 'educationattribute/:id/:visibility' => 'attributes#set_educationattribute_visibility'
  post 'workattribute/:id/:visibility' => 'attributes#set_workattribute_visibility'
  post 'forms/profilepicture' => 'attributes#profilepicture_form'
  post 'forms/backgroundpicture' => 'attributes#backgroundpicture_form'
  get 'verify/email/:code' => 'attributes#verify_email'
  get 'verify/phone/:code' => 'attributes#verify_phone'
  post 'resend/email' => 'attributes#resend_email_code'
  post 'resend/phone' => 'attributes#resend_phone_code'
  
# utility
  get 'utility/country' => 'utility#country'
  get 'utility/verifieds' => 'utility#verifieds'
  get 'utility/csrf' => 'utility#csrf', :format => :js
  post 'utility/setLocale' => 'utility#setLocale'

# admin
  scope "/admin" do
    get 'reset_cache' => 'admin#reset_cache'
    get 'stats' => 'admin#stats'
  end

# authentication
  resources :sessions
  get "login" => "sessions#new", :as => 'login'
  get "logout" => "sessions#destroy", :as => "logout" 
  get 'signup' => "users#new", :as => "signup"
  match '/auth/:provider/callback' => 'authcallbacks#create'
  match '/auth/failure' => 'authcallbacks#fail'

# other pages
  root :to => 'pages#show', :id => 'publiclanding'
  match "/pages/*id" => 'pages#show', :as => :page, :format => false
  resources :blog, :as => :posts, :controller => 'posts'
  get "/marketplaces" => 'pages#show', :id => 'marketplaces'
  get "/usecredport" => 'pages#show', :id => 'usecredport'
  get "/howitworks" => 'pages#show', :id => 'howitworks'
  get "/tos" => 'pages#show', :id => 'tos'
  get "/privacy" => 'pages#show', :id => 'privacy'
  get "/about" => 'pages#show', :id => 'about'
  get "/webcred" => "pages#show", :id => 'webcred'
  get "/faq" => "pages#show", :id => 'faq'
  get '/docs/api' => 'pages#api', :id => 'api'
  get '/docs/ux' => 'pages#ux' , :id => 'ux'
  get 'impressum' => 'pages#show', :id => 'impressum'

  get '/nam' => 'users#show', :id => '2a681'
  get '/connor' => 'users#show', :id => '3a681'
  get '/samir' => 'users#show', :id => '7a681'
  
  namespace :api, :defaults => {:format => :json} do
    namespace :v1 do
      get 'me' => 'api#me'
      resources :reviews
      resources :users do
        get 'education' => 'users#education'
        get 'work' => 'users#work'
        get 'verifications' => 'users#verifications'
        get 'commoninterests' => 'users#commoninterests'
        get 'commonconnections' => 'users#commonconnections'
        get 'stats' => 'users#stats'
        resources :identities
        resources :reviews
      end
    end
  end
end

app/models/application.rb
class Application < ActiveRecord::Base
  attr_accessible :name, :entity, :redirect_uri, :entity_attributes
  
  has_many :connection_contexts
  has_many :identity_contexts
  has_many :entity_contexts
  belongs_to :entity
  accepts_nested_attributes_for :entity

  belongs_to :user

  validates :name, :presence => true, :uniqueness => true
  validates_associated :entity, :if => :not_credport
  validates :redirect_uri, :presence => true, :redirect_uri => true
  def not_credport
    name != 'credport'
  end

  # Doorkeeper related stuff
  has_one :doorkeeper_application, :class_name => "Doorkeeper::Application"
  after_create :create_doorkeeper_application_callback

  def create_doorkeeper_application_callback
    self.create_doorkeeper_application!(:name => self.name, :redirect_uri => self.redirect_uri)
  end

  after_save :save_redirect_uri
  def save_redirect_uri
    self.doorkeeper_application.update_attribute :redirect_uri, self.redirect_uri
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include ApplicationHelper
  protect_from_forgery
    
  before_filter :set_locale
   
  def set_locale
    session[:locale] = params[:tlocale] unless session[:locale]
    session[:locale] = params[:locale] if params[:locale]
    I18n.locale = session[:locale] || I18n.default_locale
  end
 
end

app/helpers/application_helper.rb
module ApplicationHelper
  
  # Authentication
  def current_user
    if session.has_key?(:user_id) and ( @current_user.nil? or (session[:user_id] != @current_user.id))
      @current_user = User.find_by_id(session[:user_id])
    end
    @current_user 
  end

  def set_return_redirect(meta = {})
    if session[:redirect_hash].nil?
      meta[:expires_in] = 10.minutes.from_now unless meta.has_key? :expires_in
      session[:redirect_hash] = meta
    end
  end

  def authenticate_user!(meta = {})
    if !current_user
      meta[:uri] = request.url unless meta.has_key? :uri
      meta[:title] = "LogIn Required" unless meta.has_key? :title
      meta[:text] = "Please login (or signup) to see #{meta[:uri]}" unless meta.has_key? :text
      meta[:return_text] = "Return to #{URI(meta[:uri]).host}" unless meta.has_key? :return_text
      meta[:display] = true
      meta[:expires_in] = 10.minutes.from_now unless meta.has_key? :expires_in
      session[:redirect_hash] = meta
      flash[meta[:title]] = meta[:text]
      redirect_to new_session_path
    end
  end

  def authenticate_ownership(object, admin_access = true)
    render :file => "public/401.html", :status => :unauthorized, :layout => false unless object.user == current_user or (admin_access and Rails.configuration.credport_admins.include?(current_user.id.to_s))
  end

  def redirect_back(*params)
    
    uri = session[:redirect_hash][:uri] if session.has_key? :redirect_hash and session[:redirect_hash][:expires_in] > DateTime.now
    session[:redirect_hash] = nil

    if uri
      redirect_to uri
    else
      if request.env['omniauth.origin']
        redirect_to request.env['omniauth.origin']
      else
        redirect_to(*params)
      end
    end
  end

  def authenticate_admin!
    raise ActionController::RoutingError.new('Not Found') unless current_user and Rails.configuration.blog_admins.include? current_user.id.to_s
  end


  # Stats

  def mixpanel
    @mixpanel = Mixpanel::Tracker.new Rails.configuration.mixpanel_key, {}
  end

  # API
  def escape_objects(object)
    if object.class == Hash or object.class.ancestors.include? Hash
      ret = {}
      object.each{|sym, val| ret[sym] = escape_objects(val) }
      ret
    elsif object.class == Array
      object.map{|val| escape_objects val}
    else
      ERB::Util.h object
    end
  end

  def include_parameter(key)
    params.has_key?(:include) and params[:include].split(',').include?(key)
  end

  def include_education?
    include_parameter 'education'
  end

  def include_work?
    include_parameter 'work'
  end

  def include_stats?
    include_parameter 'stats'
  end

  def include_verifications?
    include_parameter 'verifications'
  end

  def include_reviews?
    include_parameter 'reviews'
  end

  def getStats
    viewer = params.has_key?(:viewer) ? User.find_param(params[:viewer]) : current_user
    if viewer.nil? or viewer == @user
      @stats = Rails.cache.fetch("api-stats-without-#{@user.cache_key}", :expires_in => 2.hours){ Connection.stats_without_viewer(@user)}
    else
      @stats = Rails.cache.fetch("api-stats-without-#{@user.cache_key}-#{viewer.cache_key}", :expires_in => 2.hours){Connection.stats_with_viewer(viewer, @user)}
    end
    @stats[:common_connections] = {
      :number => @stats[:common_connections],
      :title => t('Common Connections'),
      :desc => t('Number of connections you both share'),
      :image => "https://credport-assets.s3.amazonaws.com" + ActionController::Base.helpers.asset_path("community.png")
    }
    @stats[:common_interests] = {
      :number => @stats[:common_interests],
      :title => t('Common Interests'),
      :desc => t('Number of interests you both share'),
      :image => "https://credport-assets.s3.amazonaws.com" + ActionController::Base.helpers.asset_path("commoninterest.png")
    }
    @stats[:reviews] = {
      :number => @stats[:reviews],
      :title => t('Reviews'),
      :desc => t('Number of reviews'),
      :image => "https://credport-assets.s3.amazonaws.com" + ActionController::Base.helpers.asset_path("reviews.png")
    }
    @stats[:degree_of_seperation] = {
      :number => @stats[:degree_of_seperation],
      :title => t('Degrees of separation'),
      :desc => t('How many steps away you are'),
      :image => "https://credport-assets.s3.amazonaws.com" + ActionController::Base.helpers.asset_path("dos.png")
    }
    @stats[:accounts] = {
      :number => @stats[:accounts],
      :title => t('Accounts'),
      :desc => t('Number of verified accounts'),
      :image =>"https://credport-assets.s3.amazonaws.com" +  ActionController::Base.helpers.asset_path("accounts.png")
    }
    @stats[:verifications] = {
      :number => @stats[:verifications],
      :title => t('Verifications'),
      :desc => t('Number of emails/phones'),
      :image => "https://credport-assets.s3.amazonaws.com" + ActionController::Base.helpers.asset_path("verifications.png")
    }
    @stats
  end

  # Actual helper functions
  def get_domain(url)
    return 'undefined' unless url
    url = URI(url).host
    if url.split('.').length > 1
      url.split( "." 
)[-2,2].join(".")
    else
      url
    end
  end
end

app/views/doorkeeper/applications/_form.html.erb
<%= form_for([:oauth, application]) do |f| %>
  <fieldset>
    <% if application.errors.any? %>
      <div class="alert-message error" data-alert><a class="close" href="#">×</a><p>Whoops! Check your form for possible errors</p></div>
    <% end %>

    <div class="clearfix">
      <%= f.label :name %>
      <div class="input">
        <%= f.text_field :name %>
        <%= errors_for application, :name %>
      </div>
    </div>

    <div class="clearfix">
      <%= f.label :redirect_uri %>
      <div class="input">
        <%= f.text_field :redirect_uri %>
        <%= errors_for application, :redirect_uri %>
        <% if Doorkeeper.configuration.test_redirect_uri %>
          <span class="help-inline">Use <%= Doorkeeper.configuration.test_redirect_uri %> for local tests</span>
        <% end %>
      </div>
    </div>

    <div class="clearfix"></div>

    <div class="actions">
      <%= f.submit :Submit, :class => "btn primary" %>
      <%= link_to "Cancel", oauth_applications_path, :class => "btn" %>
    </div>
  </fieldset>
<% end %>

app/views/doorkeeper/applications/edit.html.erb
<div class="span16">
  <header class="page-header"><h2>Edit application</h2></header>
</div>

<div class="span12">
  <%= render 'form', :application => @application %>
</div>

<div class="span4">
  <h3>Actions</h3>
  <p><%= link_to 'Back to application list', oauth_applications_path %></p>
</div>

app/views/doorkeeper/applications/index.html.erb
<div class="span16">
  <header class="page-header">
    <h2>Your applications</h2>
  </header>

  <p><%= link_to 'New Application', new_oauth_application_path %></p>

  <table class="zebra-striped">
    <thead>
      <tr>
        <th>Name</th>
        <th>Callback url</th>
        <th></th>
        <th></th>
      </tr>
    </thead>
    <tbody>
      <% @applications.each do |application| %>
        <tr id="application_<%= application.id %>">
          <td><%= link_to application.name, [:oauth, application] %></td>
          <td><%= application.redirect_uri %></td>
          <td><%= link_to 'Edit', edit_oauth_application_path(application) %></td>
          <td><%= link_to 'Destroy', [:oauth, application], :data => { :confirm => 'Are you sure?' }, :method => :delete %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

</div>

app/views/doorkeeper/applications/new.html.erb
<div class="span16">
  <header class="page-header"><h2>New application</h2></header>
</div>

<div class="span12">
  <%= render 'form', :application => @application %>
</div>

<div class="span4">
  <h3>Actions</h3>
  <p><%= link_to 'Back to application list', oauth_applications_path %></p>
</div>

app/views/doorkeeper/applications/show.html.erb
<div class="span16">
  <header class="page-header">
    <h1>Application: <%= @application.name %></h1>
  </header>
</div>

<div class="span10">
  <h4>Callback url:</h4>
  <p><code><%= @application.redirect_uri %></code></p>

  <h4>Application Id:</h4>
  <p><code><%= @application.uid %></code></p>

  <h4>Secret:</h4>
  <p><code><%= @application.secret %></code></p>

  <h4>Link to authorization code:</h4>
  <p><%= link_to 'Authorize', oauth_authorization_path(:client_id => @application.uid, :redirect_uri => @application.redirect_uri, :response_type => 'code' ) %></p>
</div>

<div class="span6">
  <h3>Actions</h3>
  <p><%= link_to 'List all', oauth_applications_path %></p>
  <p><%= link_to 'Edit', edit_oauth_application_path(@application) %></p>
  <p><%= link_to 'Remove', [:oauth, @application], :method => :delete, :data => { :confirm => "Are you sure?" } %></p>
</div>