config/routes.rb
Credport::Application.routes.draw do
  use_doorkeeper do
    skip_controllers :applications
  end
  scope 'admin' do
    resources :applications, :controller => 'oauth_applications' do
      resources :identity_contexts
      resources :entity_contexts
      resources :connection_contexts
    end
  end
  match 'redirect_back' => 'oauth_applications#redirect_back_from_signup'

  mount DjMon::Engine => 'dj_mon'
  match '/auth/:provider/callback' => 'authcallbacks#create'

  # current_user routes
  get 'me' => 'users#me'
  get 'me/recommendations_to_approve' => 'reviews#me_to_approve'

  # user routes
  resources :u , :as => :users, :controller => "users" do
    post 'emails' => 'attributes#add_email_to_verify'
    post 'phones' => 'attributes#add_phone_to_verify'
    post 'websites' => 'attributes#add_website_to_verify' 
    post 'websites/:id/check' => 'attributes#check_website'
    post 'name' => 'attributes#change_name'
    post 'tagline' => 'attributes#change_tagline'
    post 'profilepictures' => 'attributes#add_profile_picture'
    post 'backgroundpicture' => 'attributes#add_background_picture'
    post 'remove_profile_picture' => "attributes#remove_profile_picture"
    
    # credport recommendations
    post 'reviews' => 'reviews#create'
    post 'reviews/request_by_email' => 'reviews#request_by_email'
    put 'reviews/:id/approve' => 'reviews#approve'
    delete 'reviews/:id' => 'reviews#destroy'
    get 'review' => 'reviews#show'
    put 'review' => 'reviews#update'
    get ':mode' => 'users#show'
  end

  post 'educationattribute/:id/:visibility' => 'attributes#set_educationattribute_visibility'
  post 'workattribute/:id/:visibility' => 'attributes#set_workattribute_visibility'
  post 'forms/profilepicture' => 'attributes#profilepicture_form'
  post 'forms/backgroundpicture' => 'attributes#backgroundpicture_form'
  get 'verify/email/:code' => 'attributes#verify_email'
  get 'verify/phone/:code' => 'attributes#verify_phone'
  post 'resend/email' => 'attributes#resend_email_code'
  post 'resend/phone' => 'attributes#resend_phone_code'
  
# utility
  get 'utility/country' => 'utility#country'
  get 'utility/verifieds' => 'utility#verifieds'
  get 'utility/csrf' => 'utility#csrf', :format => :js
  post 'utility/setLocale' => 'utility#setLocale'

# admin
  scope "/admin" do
    get 'reset_cache' => 'admin#reset_cache'
    get 'stats' => 'admin#stats'
  end

# authentication
  resources :sessions
  get "login" => "sessions#new", :as => 'login'
  get "logout" => "sessions#destroy", :as => "logout" 
  get 'signup' => "users#new", :as => "signup"
  match '/auth/:provider/callback' => 'authcallbacks#create'
  match '/auth/failure' => 'authcallbacks#fail'

# other pages
  root :to => 'pages#show', :id => 'publiclanding'
  match "/pages/*id" => 'pages#show', :as => :page, :format => false
  resources :blog, :as => :posts, :controller => 'posts'
  get "/marketplaces" => 'pages#show', :id => 'marketplaces'
  get "/usecredport" => 'pages#show', :id => 'usecredport'
  get "/howitworks" => 'pages#show', :id => 'howitworks'
  get "/tos" => 'pages#show', :id => 'tos'
  get "/privacy" => 'pages#show', :id => 'privacy'
  get "/about" => 'pages#show', :id => 'about'
  get "/webcred" => "pages#show", :id => 'webcred'
  get "/faq" => "pages#show", :id => 'faq'
  get '/docs/api' => 'pages#api', :id => 'api'
  get '/docs/ux' => 'pages#ux' , :id => 'ux'
  get 'impressum' => 'pages#show', :id => 'impressum'

  get '/nam' => 'users#show', :id => '2a681'
  get '/connor' => 'users#show', :id => '3a681'
  get '/samir' => 'users#show', :id => '7a681'
  
  namespace :api, :defaults => {:format => :json} do
    namespace :v1 do
      get 'me' => 'api#me'
      resources :reviews
      resources :users do
        get 'education' => 'users#education'
        get 'work' => 'users#work'
        get 'verifications' => 'users#verifications'
        get 'commoninterests' => 'users#commoninterests'
        get 'commonconnections' => 'users#commonconnections'
        get 'stats' => 'users#stats'
        resources :identities
        resources :reviews
      end
    end
  end
end

app/models/post.rb
class Post < ActiveRecord::Base
  attr_accessible :body, :title, :summary
  
  belongs_to :user
  validates :body, :presence => true
  validates :title, :presence => true

  def to_param
    "#{id}-#{title.gsub(/[^a-z0-9]+/i, '-')}"
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_filter :prepare
  before_filter :authenticate_user!, :only => [:new, :create]
  caches_action :show, :cache_path => :show_cache_path.to_proc, :expires_in => 4.hours
  # caches_action :index, :cache_path => :index_cache_path.to_proc
  def index_cache_path
    return "blog-index-#{current_user ? current_user.id : 0}-#{I18n.locale}"
  end
  def show_cache_path
    @post = Post.find(params[:id].split('-').first)
    return "blog-#{@post.cache_key}-#{current_user ? current_user.id : 0}-#{I18n.locale}"
  end
  def index
    @posts = Post.order("created_at DESC").all

    set_meta_tags({
      :title => "Credport Blog",
      :description => "Credport's Blog with thoughts on Collaborative Consumption and Startups in general",
      :keywords => ['collaborative consumption', 'sharing economy', 'blog'],
      :canonical => 'http://www.credport.org/blog',
      :open_graph => {
        :title => "Credport Blog",
        :description => "Credport's Blog with thoughts on Collaborative Consumption and Startups in general",
        :url => 'http://www.credport.org/blog',
        :type => 'blog',
        :image => ActionController::Base.helpers.asset_path("credportsquare.png"),
        :site_name => 'Credport'
      }
      })
    
  end

  def show
    @post = Post.find(params[:id].split('-').first)
    set_meta_tags({
      :title => "Credport - #{@post.title}",
      :description => @post.body,
      :keywords => ['collaborative consumption', 'sharing economy', 'blog'],
      :canonical => post_url(@post),
      :open_graph => {
        :title => @post.title,
        :description => ActionController::Base.helpers.truncate(ActionController::Base.helpers.strip_tags(@post.body).gsub(/\s+/, ' '), :length => 200),
        :url => post_url(@post),
        :type => 'article',
        :image => ActionController::Base.helpers.asset_path("credportsquare.png"),
        :site_name => 'Credport'
      }
      })
  end

  def prepare
    @markdown = Redcarpet::Markdown.new(Redcarpet::Render::HTML,
        :autolink => true, :space_after_headers => true, :lax_spacing => true)
  end

  def new
    raise ActionController::RoutingError.new('Not Found') unless Rails.configuration.blog_admins.include? current_user.id.to_s
    @post = Post.new
  end

  def edit
    raise ActionController::RoutingError.new('Not Found') unless Rails.configuration.blog_admins.include? current_user.id.to_s
    @post = Post.find(params[:id].split('-').first)
  end

  def update
    raise ActionController::RoutingError.new('Not Found') unless Rails.configuration.blog_admins.include? current_user.id.to_s
    @post = Post.find(params[:id].split('-').first)
    @post.update_attributes params[:post]
    redirect_to post_path(@post)
  end

  def authenticate
    authenticate_or_request_with_http_basic do |username, password|
      username == "foo" && password == "bar"
    end
  end
  def create
    raise ActionController::RoutingError.new('Not Found') unless Rails.configuration.blog_admins.include? current_user.id.to_s
    @post = current_user.posts.build(params[:post])
    if @post.save
      redirect_to post_path(@post)
    else
      ap @post.errors
      redirect_to new_post_path
    end
  end

end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_blognav.html.erb
<% cache 'blognav', :expires_in => 1.hour do %>
<aside id="blognav">
  <h3><%= link_to 'Credport Blog', posts_path %></h3>
  <p>This is Credport's Blog talking about Collaborative Consumption, Online Identity and general musings of running a startup in Berlin as 20-somethings.</p>
  <p>What is Credport? <a href="/">Credport</a> is your online place to unify your reputation online. <%= link_to "Learn More", root_path %></p>
  
  <h5>Previous Blog posts</h5>
  <ul>
    <% for post in Post.order("created_at DESC").limit(10) %>
      <li><%= link_to post.title, post_path(post) %></li>
    <% end %>
  </ul>
</aside>
<% end %>

app/views/posts/_form.html.erb
<%= form_for @post do |f| %>
  <%= f.label :title, "Title" %>  
  <%= f.text_field :title %>
  <%= f.label :summary, "Summary" %>
  <%= f.text_area :summary %>
  <%= f.label :body, "Body" %>
  <%= f.text_area :body %>
  <%= f.submit "Submit", :disable_with => 'Submiting...' %>
<% end %>

app/views/posts/edit.html.erb
<h1>Edit Post</h1>
<%= render :partial => "form" %>

app/views/posts/index.html.erb
<%= render 'blognav' %>

<% if !@posts.blank? %>
  <% cache ['index', @posts.first] do %>
  <% for post in @posts %>
    <article>
      <header>
        <h2>  <%= link_to post.title, post_path(post) %></h2>
        <h5>by <%= link_to post.user.name, user_path(post.user) %>  <%= time_ago_in_words(post.updated_at) %> ago</h5>
      </header>
      <%=raw @markdown.render (post.summary.blank? ? post.body : post.summary) %>
      <footer>
        <% if !post.summary.blank? %>
          <p><%= link_to "Read more", post_path(post)  %></p>
        <% else %>
          <p><%= link_to "Click here to comment", post_path(post) + '#comments' %></p>
        <% end %>
        
      </footer>
    </article>
  <% end %>
  <% end %>
<% else %>
  
<% end %>

app/views/posts/new.html.erb
<h1>New Post</h1>
<%= render :partial => "form" %>

app/views/posts/show.html.erb
<%= render 'blognav' %>
<% cache @post do %>
<article>
      <header>
        <h2>  <%= link_to @post.title, post_path(@post) %></h2>
        <h5>by <%= link_to @post.user.name, user_path(@post.user) %>  <%= time_ago_in_words(@post.updated_at) %> ago</h5>
      </header>
      <%=raw @markdown.render @post.body %>
      <div class="addthis_toolbox addthis_default_style ">
<a class="addthis_button_facebook_like" fb:like:layout="button_count"></a>
<a class="addthis_button_tweet"></a>
<a class="addthis_button_google_plusone" g:plusone:size="medium"></a>
<a class="addthis_counter addthis_pill_style"></a>
</div>
<script type="text/javascript" src="https://s7.addthis.com/js/250/addthis_widget.js#pubid=ra-4fc4dc1b76c760cc"></script>
<!-- AddThis Button END -->

<section></section>

<div id="comments">
  <div id="disqus_thread"></div>
</div>

        <script type="text/javascript">
            /* * * CONFIGURATION VARIABLES: EDIT BEFORE PASTING INTO YOUR WEBPAGE * * */
            var disqus_shortname = 'webcredcoblog'; // required: replace example with your forum shortname

            /* * * DON'T EDIT BELOW THIS LINE * * */
            (function() {
                var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
                dsq.src = 'https://' + disqus_shortname + '.disqus.com/embed.js';
                (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);
            })();
        </script>
        <noscript>Please enable JavaScript to view the <a href="http://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>
        <a href="http://disqus.com" class="dsq-brlink">comments powered by <span class="logo-disqus">Disqus</span></a>
        

<p></p>
  <a href="/blog.rss" class="feed">Subscribe</a>
</article>
<script>
  mixpanel.track('Blog:View', {id: '<%= @post.id %>'});
</script>
<% end %>

app/views/posts/tagged.html.erb
<h1>Posts tagged '<%= params[:tag] %>'</h1>
<% if !@posts.blank? %>
  <% for post in @posts %>
    <article>
      <header>
        <h2>  <%= link_to post.title, blog_path(post) %></h2>
        <h5>by <a href="<%= post.authorurl %>"><%= post.author %></a>  <%= time_ago_in_words(post.date) %> ago</h5>
      </header>
      <%=raw @markdown.render post.body %>
      <footer>
        <% if !post.tags.blank? %>
        <p>
         Tags:
          <%= raw post.tags.map{|tag| "<a href='/blog/tagged/#{tag}'>#{tag}</a>"}.join(', ')%>
          </p>
        <% else %>
          
        <% end %>
        <p><%= link_to "Click here to comment", blog_path(post) + '#comments' %></p>
      </footer>
    </article>
  <% end %>
<% else %>
  
<% end %>