config/routes.rb
Credport::Application.routes.draw do
  use_doorkeeper do
    skip_controllers :applications
  end
  scope 'admin' do
    resources :applications, :controller => 'oauth_applications' do
      resources :identity_contexts
      resources :entity_contexts
      resources :connection_contexts
    end
  end
  match 'redirect_back' => 'oauth_applications#redirect_back_from_signup'

  mount DjMon::Engine => 'dj_mon'
  match '/auth/:provider/callback' => 'authcallbacks#create'

  # current_user routes
  get 'me' => 'users#me'
  get 'me/recommendations_to_approve' => 'reviews#me_to_approve'

  # user routes
  resources :u , :as => :users, :controller => "users" do
    post 'emails' => 'attributes#add_email_to_verify'
    post 'phones' => 'attributes#add_phone_to_verify'
    post 'websites' => 'attributes#add_website_to_verify' 
    post 'websites/:id/check' => 'attributes#check_website'
    post 'name' => 'attributes#change_name'
    post 'tagline' => 'attributes#change_tagline'
    post 'profilepictures' => 'attributes#add_profile_picture'
    post 'backgroundpicture' => 'attributes#add_background_picture'
    post 'remove_profile_picture' => "attributes#remove_profile_picture"
    
    # credport recommendations
    post 'reviews' => 'reviews#create'
    post 'reviews/request_by_email' => 'reviews#request_by_email'
    put 'reviews/:id/approve' => 'reviews#approve'
    delete 'reviews/:id' => 'reviews#destroy'
    get 'review' => 'reviews#show'
    put 'review' => 'reviews#update'
    get ':mode' => 'users#show'
  end

  post 'educationattribute/:id/:visibility' => 'attributes#set_educationattribute_visibility'
  post 'workattribute/:id/:visibility' => 'attributes#set_workattribute_visibility'
  post 'forms/profilepicture' => 'attributes#profilepicture_form'
  post 'forms/backgroundpicture' => 'attributes#backgroundpicture_form'
  get 'verify/email/:code' => 'attributes#verify_email'
  get 'verify/phone/:code' => 'attributes#verify_phone'
  post 'resend/email' => 'attributes#resend_email_code'
  post 'resend/phone' => 'attributes#resend_phone_code'
  
# utility
  get 'utility/country' => 'utility#country'
  get 'utility/verifieds' => 'utility#verifieds'
  get 'utility/csrf' => 'utility#csrf', :format => :js
  post 'utility/setLocale' => 'utility#setLocale'

# admin
  scope "/admin" do
    get 'reset_cache' => 'admin#reset_cache'
    get 'stats' => 'admin#stats'
  end

# authentication
  resources :sessions
  get "login" => "sessions#new", :as => 'login'
  get "logout" => "sessions#destroy", :as => "logout" 
  get 'signup' => "users#new", :as => "signup"
  match '/auth/:provider/callback' => 'authcallbacks#create'
  match '/auth/failure' => 'authcallbacks#fail'

# other pages
  root :to => 'pages#show', :id => 'publiclanding'
  match "/pages/*id" => 'pages#show', :as => :page, :format => false
  resources :blog, :as => :posts, :controller => 'posts'
  get "/marketplaces" => 'pages#show', :id => 'marketplaces'
  get "/usecredport" => 'pages#show', :id => 'usecredport'
  get "/howitworks" => 'pages#show', :id => 'howitworks'
  get "/tos" => 'pages#show', :id => 'tos'
  get "/privacy" => 'pages#show', :id => 'privacy'
  get "/about" => 'pages#show', :id => 'about'
  get "/webcred" => "pages#show", :id => 'webcred'
  get "/faq" => "pages#show", :id => 'faq'
  get '/docs/api' => 'pages#api', :id => 'api'
  get '/docs/ux' => 'pages#ux' , :id => 'ux'
  get 'impressum' => 'pages#show', :id => 'impressum'

  get '/nam' => 'users#show', :id => '2a681'
  get '/connor' => 'users#show', :id => '3a681'
  get '/samir' => 'users#show', :id => '7a681'
  
  namespace :api, :defaults => {:format => :json} do
    namespace :v1 do
      get 'me' => 'api#me'
      resources :reviews
      resources :users do
        get 'education' => 'users#education'
        get 'work' => 'users#work'
        get 'verifications' => 'users#verifications'
        get 'commoninterests' => 'users#commoninterests'
        get 'commonconnections' => 'users#commonconnections'
        get 'stats' => 'users#stats'
        resources :identities
        resources :reviews
      end
    end
  end
end

app/controllers/oauth_applications_controller.rb
class OauthApplicationsController < ApplicationController
  before_filter :authenticate_user!

  def index
    @applications = current_user.applications
    @applications = Application.all if Rails.configuration.credport_admins.include? current_user.id.to_s
  end

  def show
    @application = Application.find(params[:id])
    authenticate_ownership(@application)
  end


  def edit
    @application = Application.find(params[:id])
  end

  def update
    @application = Application.find(params[:id])
    if @application.update_attributes params[:application]
      redirect_to application_path(@application)
    else
      render 'edit'
    end
  end

  def new
    @application = Application.new
    @entity = @application.build_entity
  end

  def create
    @application = current_user.applications.build params[:application]
    @application.entity.context = EntityContext.find_by_name('credport_application_context') if @application.entity
    if @application.save
      redirect_to application_path(@application)
    else
      render 'new'
    end
  end

  def redirect_back_from_signup
    redirect_back root_path
  end
end

app/helpers/oauth_applications_helper.rb
module OauthApplicationsHelper
end

app/views/oauth_applications/_form.html.erb
<%= form_for @application do |f| %>
<% if @application.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@application.errors.count, "error") %> prohibited this Application from being saved:</h2>

    <ul>
    <% @application.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>
  <%= f.label :name %><br />
  <%= f.text_field :name %>
  <%= f.label :redirect_uri %><br />
  <%= f.text_field :redirect_uri %>
  <%= f.fields_for :entity do |entity| %>
    <%= f.label :uid %><br />
    <%= entity.text_field :uid %>
    <%= f.label :name %><br />
    <%= entity.text_field :name %>
    <%= f.label :image %><br />
    <%= entity.text_field :image %>
    <%= f.label :url %><br />
    <%= entity.text_field :url %>
  <% end %>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end -%>

app/views/oauth_applications/edit.html.erb
<h3>Settings</h3>

<%= render 'form' %>

app/views/oauth_applications/index.html.erb
<% if !@applications.blank? %>
  <h1>Your Applications:</h1>
  <table>
    <thead>
      <tr>
        <th>Identifier</th>
        <th>Edit</th>
        <th>Created At</th>
        <th>Updated At</th>
      </tr>
    </thead>
    
  
  <% for application in @applications %>
    <tr>
      <td><%= link_to application.name, application_path(application)  %></td>
      <td><%= link_to "Edit", edit_application_path(application)  %></td>
      <td><%= application.created_at  %></td>
      <td><%= application.updated_at %></td>
    </tr>
    
  <% end %>
  </table>
<% else %>
  <h1>You currently have no applications under management</h1>
  
<% end %>   

<h3><%= link_to "Create new Application", new_application_path %></h3>  

app/views/oauth_applications/new.html.erb
<h1>Create new Application</h1>

<%= render 'form' %>

app/views/oauth_applications/show.html.erb
<h1>Application</h1>
<div class="row">
  <div class="eight columns">
    <h3>Settings:</h3>
    <h4>Link to authorization code:</h4>
    <p><%= link_to 'Authorize', oauth_authorization_path(:client_id => @application.doorkeeper_application.uid, :redirect_uri => @application.doorkeeper_application.redirect_uri, :response_type => 'code' ) %></p>
    <table>
      <tbody>
        <tr>
          <th>Identifier: </th>
          <td><%= @application.name %></td>
        </tr>
        <tr>
          <th>Key:</th>
          <td><%= @application.doorkeeper_application.uid %></td>
        </tr>
        <tr>
          <th>Secret:</th>
          <td><%= @application.doorkeeper_application.secret %></td>
        </tr>
        <tr>
          <th>Redirect URI:</th>
          <td><%= @application.doorkeeper_application.redirect_uri %></td>
        </tr>
      </tbody>
    </table>
    <%= link_to "Edit Application", edit_application_path(@application)  %>
    <h3>Application Object</h3>
    <p>The Object that represents your application through the contexts. It should be used by third parties to give a sense of context.</p>
    <div class="object-box">
      <img src="<%= @application.entity.image %>" alt=" ">
      <div class="content-box">
        <div class="title"><%= link_to @application.entity.name, @application.entity.url %></div>
        <div class="subtitle"><%= @application.entity.context.title %></div>
      </div>
    </div>
   
  </div>
  <div class="four columns">
    <% if @application.user %>
      <h3>Application Owner</h3>
      <div id="credport-button">
      </div>
      <script type="text/javascript">
        window.credport = {
          user: {
            id: '<%= @application.user.to_param %>'
          },
          buttontext: "We have partnered with Credport to help you build a portable trustworthy profile. Credport increases your chance of a transaction (like a good eBay rating) and lets you bring your reputation anywhere"
        };
        (function() {
            var script = document.createElement('script');
            script.src   = 'https://s3.amazonaws.com/credport-assets/assets/badge.1.1.js';
            script.async = true;
            var entry = document.getElementsByTagName('script')[0];
            entry.parentNode.insertBefore(script, entry);
          })();
      </script>
    <% end %>
  </div>
</div>

<h3>Data Contexts on Credport</h3>

<% if !@application.connection_contexts.blank? %>
  <h4>Connection Contexts</h4>
  <table>
    <thead>
      <tr>
        <th>Name</th>
        <th>Async</th>
        <th>Cardinality</th>
        <th>Connection Type</th>
        <th>Properties</th>
      </tr>
    </thead>
  <% for context in @application.connection_contexts %>
    <tr>
      <td><%= context.name %></td>
      <td><%= context.async %></td>
      <td><%= context.cardinality %></td>
      <td><%= context.connection_type %></td>
      <td><%= context.properties %></td>
    </tr>
  <% end %>
  </table>
<% else %>
  <h6>There are currently now ConnectionContexts associated with this application</h6>
<% end %>

<p><%= link_to "Create a new ConnectionContext", new_application_connection_context_path(@application) %></p>

<% if !@application.identity_contexts.blank? %>
  <h4>Identity Contexts</h4>
  <table>
    <thead>
      <tr>
        <th>Name</th>
        <th>Title</th>
      </tr>
    </thead>
  <% for context in @application.identity_contexts %>
    <tr>
      <td><%= context.name %></td>
      <td><%= context.title %></td>
    </tr>
  <% end %>
  </table>
<% else %>
  <h6>There are currently now IdentityContexts associated with this application</h6>
<% end %>

<p><%= link_to "Create a new IdentityContext", new_application_identity_context_path(@application) %></p>

<% if !@application.entity_contexts.blank? %>
  <h4>Entity Contexts</h4>
  <table>
    <thead>
      <tr>
        <th>Name</th>
        <th>Title</th>
      </tr>
    </thead>
  <% for context in @application.entity_contexts %>
    <tr>
      <td><%= context.name %></td>
      <td><%= context.title %></td>
    </tr>
  <% end %>
  </table>
<% else %>
  <h6>There are currently now EntityContexts associated with this application</h6>
<% end %>

<p><%= link_to "Create a new EntityContext", new_application_entity_context_path(@application) %></p>